#!/usr/bin/env python3
"""Artifact writers for the Orbit settings generation boundary."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False) as stream:
        stream.write(content)
        temporary = Path(stream.name)
    os.replace(temporary, path)


def lua_string(value: object) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def write_window_rules(values: list[dict], destination: Path) -> None:
    lines = ["-- Generated by orbit-settings. Do not edit manually.", ""]
    for rule in sorted(values, key=lambda item: (int(item.get("priority", 100)), str(item.get("id", "")))):
        if rule.get("kind", "simple") == "custom":
            lines.extend([str(rule.get("custom_source", "")), ""])
            continue
        match_type = str(rule.get("match_type", "class"))
        match_value = str(rule.get("match_pattern") or rule.get("match_value", ".*"))
        if match_type in {"class", "title"}:
            match_text = f'{match_type} = {lua_string(match_value)}'
        else:
            match_text = f'{match_type} = {"true" if str(rule.get("match_value", "true")).lower() == "true" else "false"}'
        lines.extend([
            "hl.window_rule({",
            f'    name = {lua_string(rule.get("name", "orbit-rule"))},',
            f"    match = {{ {match_text} }},",
        ])
        for key in ("float", "no_anim", "no_blur", "no_shadow", "decorate", "center", "focus_on_activate", "no_focus", "fullscreen"):
            value = rule.get("floating" if key == "float" else key)
            if isinstance(value, bool):
                lines.append(f"    {key} = {'true' if value else 'false'},")
        lines.extend(["})", ""])
    atomic_write(destination, "\n".join(lines))


def write_monitors_lua(profiles: list[dict], destination: Path) -> None:
    lines = ["-- Generated by orbit-settings. Do not edit manually.", ""]
    for profile in profiles:
        connector = str(profile.get("connector", ""))
        if not connector:
            continue
        if profile.get("active", True) is False:
            lines.extend(["hl.monitor({", f'    output = "{connector}",', "    disabled = true", "})"])
            continue
        mode = f'{int(profile.get("width", 0))}x{int(profile.get("height", 0))}@{float(profile.get("refresh_rate", 0)):.2f}'
        lines.extend(["hl.monitor({", f'    output = "{connector}",', f'    mode = "{mode}",', f'    position = "{int(profile.get("x", 0))}x{int(profile.get("y", 0))}",', "    scale = 1.0,", f'    vrr = {1 if profile.get("adaptive_sync", False) else 0}', "})"])
    atomic_write(destination, "\n".join(lines) + "\n")


def write_appearance_artifacts(values: dict, generated: Path) -> None:
    generated.mkdir(parents=True, exist_ok=True)
    atomic_write(generated / "appearance.json", json.dumps(values, indent=2) + "\n")
    style = values["style"]
    transparency = values["transparency"]
    effects = values["effects"]
    lines = ["-- Generated by orbit-settings. Do not edit manually.", "return {", f'    style = {{ button_shape = "{style["button_shape"]}", corner_radius = {int(style["corner_radius"])} }},', f'    transparency = {{ active_opacity = {float(transparency["active_opacity"])}, inactive_opacity = {float(transparency["inactive_opacity"])}, shell_opacity = {float(transparency["shell_opacity"])} }},', "    effects = {", f'        hyprglass_enabled = {str(bool(effects["hyprglass_enabled"])).lower()},', f'        hyprglass_blur_type = "{effects["hyprglass_blur_type"]}",', f'        hyprwindowshade_enabled = {str(bool(effects["hyprwindowshade_enabled"])).lower()},', f'        animations_enabled = {str(bool(effects["animations_enabled"])).lower()},', "        animations = {"]
    for group, item in effects["animations"].items():
        lines.append(f'            {group} = {{ enabled = {str(bool(item["enabled"])).lower()}, speed = {float(item["speed"])}, type = "{item["type"]}" }},')
    lines.extend(["        },", "    },", "}", ""])
    atomic_write(generated / "appearance.lua", "\n".join(lines))
