-- Generated by orbit-settings. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1200@74.93",
    position = "-71x-4",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@120.00",
    position = "1851x-4",
    scale = 1.0,
    vrr = 0
})
