-- Generated by orbit-settings. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1200@74.93",
    position = "-80x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.01",
    position = "1840x0",
    scale = 1.0,
    vrr = 0
})
