-- Generated by nwg-displays on 2026-08-06 at 19:24:13. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1200@74.93",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.01",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HEADLESS-2",
    disabled = true
})
